name: Deploy React App to AWS Elastic Beanstalk and Strapi App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Delete existing zip file for Strapi App
        run: rm -f yby-front-app.zip

      - name: Zip files for Strapi App
        run: zip -r yby-front-app.zip .

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "yby-front-app.zip"
          target: "/home/ubuntu"

      - name: SSH into EC2 and prepare environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt-get update
            sudo apt-get install -y unzip docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            unzip /home/ubuntu/yby-front-app.zip -d /home/ubuntu/yby-front-app
            cd /home/ubuntu/yby-front-app

            sudo docker ps -q | xargs -r sudo docker stop
            sudo docker rm $(sudo docker ps -aq)
            sudo docker rmi $(sudo docker images -q)
            sudo docker volume prune -f
            sudo docker network prune -f
            sudo docker system prune -a --volumes -f
            
            # Build and run the Docker container
            sudo docker build -t yby-front-app .
            sudo docker run -d -p 80:80 yby-front-app

      - name: Deployed to EC2!
        run: echo Strapi App deployed to EC2
