name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Save repository as zip
        run: |
          zip -r yby-front-app.zip .

      - name: Copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "yby-front-app.zip"
          target: "/home/ubuntu"

      - name: SSH into EC2 and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y unzip docker
            sudo usermod -aG docker $USER
            sudo systemctl start docker
            sudo systemctl enable docker
            unzip /home/ubuntu/yby-front-app.zip -d /home/ubuntu/yby-front-app
            cd /home/ubuntu/yby-front-app

            sudo docker ps -q | xargs -r sudo docker stop
            sudo docker rm $(sudo docker ps -aq)
            sudo docker rmi $(sudo docker images -q)
            sudo docker volume prune -f
            sudo docker network prune -f
            sudo docker system prune -a --volumes -f
            
            sudo docker build -t yby-front-app .
            sudo docker run -d -p 80:80 yby-front-app


      - name: Clean up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/yby-front-app.zip
            rm -rf /home/ubuntu/yby-front-app

