name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save repository as zip
        run: |
          zip -r yby-front-app.zip .

      - name: Copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "yby-front-app.zip"
          target: "/home/ubuntu"

      - name: SSH into EC2 and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            unzip yby-front-app.zip
            docker build -t yby-front-app .
            docker run -d -p 80:80 yby-front-app
            sudo cp location.conf /etc/nginx/conf.d/location.conf
            sudo systemctl restart nginx

      - name: Clean up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            rm -rf /home/ubuntu/yby-front-app.zip
            rm -rf /home/ubuntu/my-app
