name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1'

    - name: Listas folder
      run: |
          ls -la
          rm -f package-lock.json
          rm -rf node_modules
          ls -la

    - name: Install dependencies
      run: npm install --no-audit

      
    - name: Run build
      run: npm run build
      
    - name: Listas folder
      run: |
          ls -la
          ls -la
          
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Generate version label
      run: echo "::set-output name=version_label::$(date +%Y%m%d%H%M%S)-${{ github.sha }}"
      id: generate_version_label

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: yby-front-app
        environment_name: yby-front-env
        version_label: ${{ steps.generate_version_label.outputs.version_label }}
        region: us-east-1
        deployment_package: deploy.zip
        use_existing_version_if_available: true
        wait_for_environment_recovery: 120
