name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save repository as zip
        run: |
          zip -r my-app.zip .

      - name: Copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "my-app.zip"
          target: "/home/ec2-user"

      - name: SSH into EC2 and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user
            unzip my-app.zip
            docker build -t my-app .
            docker run -d -p 80:80 my-app
            CONTAINER_ID=$(docker ps -q --filter ancestor=my-app)
            docker cp location.conf $CONTAINER_ID:/etc/nginx/conf.d/location.conf
            docker exec $CONTAINER_ID nginx -s reload

      - name: Clean up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            rm -rf /home/ec2-user/my-app.zip
            rm -rf /home/ec2-user/my-app
